# Generated by Django 4.1.6 on 2023-02-15 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randrapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='river',
            name='rapid',
        ),
    ]
